```{r}
rm(list = ls())
```

```{r}
library(Seurat)
library(tidyverse)
library(parallel)
library(DoubletFinder)
```

```{r}
parasite_infection <- readRDS("/home/ubuntu/Seurat_parasite_infection.RDS")

#Set the factor levels
parasite_infection@meta.data[["stage"]] <- factor(parasite_infection@meta.data[["stage"]], levels = c("uninfected", "early", "peak", "repair"))
```

```{r}
parasite_infection.split <- SplitObject(parasite_infection, split.by = "stage") 

# loop through samples to find doublets
for (i in 1:length(parasite_infection.split)) {
  # print the sample we are on
  print(paste0("Sample ",i))
  
  # Pre-process seurat object with standard seurat workflow
  mouse.sample <- NormalizeData(parasite_infection.split[[i]])
  mouse.sample <- FindVariableFeatures(mouse.sample)
  mouse.sample <- ScaleData(mouse.sample)
  mouse.sample <- RunPCA(mouse.sample, nfeatures.print = 10)
  
  # Find significant PCs
  stdv <- mouse.sample[["pca"]]@stdev
  sum.stdv <- sum(mouse.sample[["pca"]]@stdev)
  percent.stdv <- (stdv / sum.stdv) * 100
  cumulative <- cumsum(percent.stdv)
  co1 <- which(cumulative > 90 & percent.stdv < 5)[1]
  co2 <- sort(which((percent.stdv[1:length(percent.stdv) - 1] - 
                       percent.stdv[2:length(percent.stdv)]) > 0.1), 
              decreasing = T)[1] + 1
  min.pc <- min(co1, co2)
  min.pc
  
  # finish pre-processing
  mouse.sample <- RunUMAP(mouse.sample, dims = 1:min.pc)
  mouse.sample <- FindNeighbors(object = mouse.sample, dims = 1:min.pc)              
  mouse.sample <- FindClusters(object = mouse.sample, resolution = 0.1)
  
  # pK identification (no ground-truth)
  sweep.list <- paramSweep_v3(mouse.sample, PCs = 1:min.pc, num.cores = detectCores() - 1)
  sweep.stats <- summarizeSweep(sweep.list)
  bcmvn <- find.pK(sweep.stats)
  
  # Optimal pK is the max of the bomodality coefficent (BCmvn) distribution
  bcmvn.max <- bcmvn[which.max(bcmvn$BCmetric),]
  optimal.pk <- bcmvn.max$pK
  optimal.pk <- as.numeric(levels(optimal.pk))[optimal.pk]
  
  ## Homotypic doublet proportion estimate
  annotations <- mouse.sample@meta.data$seurat_clusters
  homotypic.prop <- modelHomotypic(annotations) 
  nExp.poi <- round(optimal.pk * nrow(mouse.sample@meta.data)) ## Assuming 7.5% doublet formation rate - tailor for your dataset
  nExp.poi.adj <- round(nExp.poi * (1 - homotypic.prop))
  
  # run DoubletFinder
  mouse.sample <- doubletFinder_v3(seu = mouse.sample, 
                                   PCs = 1:min.pc, 
                                   pK = optimal.pk,
                                   nExp = nExp.poi.adj)
  metadata <- mouse.sample@meta.data
  colnames(metadata)[9] <- "doublet_finder"
  mouse.sample@meta.data <- metadata 
  
  # subset and save
  mouse.singlets <- subset(mouse.sample, doublet_finder == "Singlet")
  parasite_infection.split[[i]] <- mouse.singlets
  remove(mouse.singlets)
}

```
```{r}
# merge the splitted data back
parasite_infection <- merge(x = parasite_infection.split[[1]],
                       y = c(parasite_infection.split[[2]], 
                             parasite_infection.split[[3]],
                             parasite_infection.split[[4]]),
                       project = "parasite_infection")
parasite_infection
```

```{r}
saveRDS(parasite_infection, "parasite_infection_singlets.RDS")
```

